name: 🐞 Bug Report
description: Tell us about something not working properly
labels: [ "kind/bug", "priority/needs-triage" ]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        
        Thanks for helping make the wooak project better!

  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: I have searched the [existing issues](https://github.com/adembc/wooak/issues).
          required: true


  - type: input
    id: wooak-version
    attributes:
      label: wooak Version
      placeholder: X.X.X
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What is the OS/ARCH you are using to run wooak ?
      placeholder: macOS (darwin/amd64), macOS (darwin/arm64), Linux (linux/arm64), etc...
    validations:
      required: true


  - type: textarea
    id: description
    attributes:
      label: Description
      description: The __context__ the problem occurred in, and an __overview__ of what went wrong.
      placeholder: I was trying to... but then...
    validations:
      required: true
