blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/aryasoni98/wooak/discussions
    about: Ask questions, share ideas, or get help from the community
  - name: 📚 Documentation
    url: https://github.com/aryasoni98/wooak#readme
    about: Check our comprehensive documentation and guides
  - name: 🎃 Hacktoberfest Info
    url: https://hacktoberfest.com/participation/
    about: Learn about Hacktoberfest participation guidelines