name: 📚 Improve documentation and add usage examples
description: Enhance documentation with better examples, API documentation, and usage guides
title: "[Hacktoberfest]: Improve documentation and add usage examples"
labels: ["hacktoberfest", "hacktoberfest-accepted", "good first issue", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        🎉 Welcome to Hacktoberfest! Thank you for considering contributing to Wooak.
        
        This template is specifically for Hacktoberfest contributors. Please read our [Contributing Guidelines](CONTRIBUTING.md) and [Code of Conduct](CODE_OF_CONDUCT.md) before getting started.

  - type: dropdown
    id: contribution_type
    attributes:
      label: Contribution Type
      description: What type of contribution are you planning to make?
      options:
        - Bug Fix
        - New Feature
        - Documentation
        - Code Refactoring
        - Test Coverage
        - Performance Improvement
        - Security Enhancement
        - UI/UX Improvement
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty Level
      description: How would you rate the difficulty of this contribution?
      options:
        - Beginner - Good first issue
        - Intermediate - Some experience needed
        - Advanced - Requires deep knowledge
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Contribution Description
      description: Describe what you plan to contribute
      placeholder: Provide a clear description of your planned contribution...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why are you interested in contributing to this project?
      placeholder: Tell us what motivated you to contribute to Wooak...

  - type: textarea
    id: experience
    attributes:
      label: Relevant Experience
      description: What experience do you have with Go, SSH, or similar technologies?
      placeholder: Describe your relevant technical experience...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-contribution Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have read the Contributing Guidelines
          required: true
        - label: I have read the Code of Conduct
          required: true
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I understand this is a Hacktoberfest contribution
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue, you agree to follow our guidelines
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I understand that quality contributions are valued over quantity
          required: true

  - type: markdown
    attributes:
      value: |
        ## 📚 Issue Description
        
        Enhance documentation with better examples, API documentation, and usage guides to improve the developer and user experience.
        
        **Current Issue:**
        - Limited API documentation
        - Missing usage examples
        - Some functions lack proper documentation
        - No configuration examples
        
        **Expected Solution:**
        - Add comprehensive API documentation
        - Create usage examples and tutorials
        - Improve inline code documentation
        - Add configuration examples
        
        **Files to Modify:**
        - Update all Go files with better documentation
        - Create examples directory
        - Update README.md with more examples
        
        **Acceptance Criteria:**
        - [ ] Add API documentation
        - [ ] Create usage examples
        - [ ] Improve inline documentation
        - [ ] Add configuration examples
        - [ ] Create tutorials
        - [ ] Update README
        
        **Difficulty:** Low
        **Estimated Time:** 3-4 hours
        
        ## 🎯 Technical Details
        
        This issue focuses on improving documentation across the project:
        
        **Documentation areas to improve:**
        1. **API documentation** - Function signatures, parameters, return values
        2. **Usage examples** - Code examples, configuration samples
        3. **Inline documentation** - Go doc comments, package documentation
        4. **Tutorials** - Step-by-step guides for common tasks
        5. **Configuration guides** - Examples for different use cases
        
        **Suggested Approach:**
        1. Review existing documentation and identify gaps
        2. Add comprehensive Go doc comments
        3. Create usage examples for key features
        4. Add configuration examples
        5. Create tutorials for common workflows
        
        **Documentation types to add:**
        - Package-level documentation
        - Function and method documentation
        - Configuration examples
        - Usage tutorials
        - API reference
        - Troubleshooting guides
        
        ## 📚 Resources
        - [Go documentation guidelines](https://golang.org/doc/effective_go.html#commentary)
        - [Go doc command](https://golang.org/cmd/go/#hdr-Show_documentation_for_package_or_symbol)
        - [Markdown documentation best practices](https://www.markdownguide.org/basic-syntax/)
