name: ⌨️ Add comprehensive keyboard shortcuts documentation
description: Create comprehensive documentation for all keyboard shortcuts and add a help system
title: "[Hacktoberfest]: Add comprehensive keyboard shortcuts documentation"
labels: ["hacktoberfest", "hacktoberfest-accepted", "good first issue", "documentation", "ui"]
body:
  - type: markdown
    attributes:
      value: |
        🎉 Welcome to Hacktoberfest! Thank you for considering contributing to Wooak.
        
        This template is specifically for Hacktoberfest contributors. Please read our [Contributing Guidelines](CONTRIBUTING.md) and [Code of Conduct](CODE_OF_CONDUCT.md) before getting started.

  - type: dropdown
    id: contribution_type
    attributes:
      label: Contribution Type
      description: What type of contribution are you planning to make?
      options:
        - Bug Fix
        - New Feature
        - Documentation
        - Code Refactoring
        - Test Coverage
        - Performance Improvement
        - Security Enhancement
        - UI/UX Improvement
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: Difficulty Level
      description: How would you rate the difficulty of this contribution?
      options:
        - Beginner - Good first issue
        - Intermediate - Some experience needed
        - Advanced - Requires deep knowledge
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Contribution Description
      description: Describe what you plan to contribute
      placeholder: Provide a clear description of your planned contribution...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why are you interested in contributing to this project?
      placeholder: Tell us what motivated you to contribute to Wooak...

  - type: textarea
    id: experience
    attributes:
      label: Relevant Experience
      description: What experience do you have with Go, SSH, or similar technologies?
      placeholder: Describe your relevant technical experience...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-contribution Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have read the Contributing Guidelines
          required: true
        - label: I have read the Code of Conduct
          required: true
        - label: I have checked existing issues to avoid duplicates
          required: true
        - label: I understand this is a Hacktoberfest contribution
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Agreement
      description: By submitting this issue, you agree to follow our guidelines
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
        - label: I understand that quality contributions are valued over quantity
          required: true

  - type: markdown
    attributes:
      value: |
        ## ⌨️ Issue Description
        
        Create comprehensive documentation for all keyboard shortcuts and add a help system within the application.
        
        **Current Issue:**
        - Limited keyboard shortcuts documentation
        - No in-app help system
        - Users may not discover all available shortcuts
        - No quick reference guide
        
        **Expected Solution:**
        - Document all keyboard shortcuts
        - Add in-app help system
        - Create keyboard shortcuts reference
        - Add help command
        
        **Files to Modify:**
        - `internal/adapters/ui/handlers.go`
        - `README.md`
        - Add help system to TUI
        
        **Acceptance Criteria:**
        - [ ] Document all shortcuts
        - [ ] Add in-app help system
        - [ ] Create shortcuts reference
        - [ ] Add help command
        - [ ] Update documentation
        - [ ] Add help tests
        
        **Difficulty:** Low
        **Estimated Time:** 2-3 hours
        
        ## 🎯 Technical Details
        
        This issue involves creating comprehensive keyboard shortcuts documentation and help system:
        
        **Areas to document:**
        1. **Main interface shortcuts** - Navigation, selection, actions
        2. **Form shortcuts** - Input fields, validation, submission
        3. **AI panel shortcuts** - Query input, response handling
        4. **Security panel shortcuts** - Configuration, validation
        
        **Suggested Approach:**
        1. Audit all existing keyboard shortcuts
        2. Create comprehensive documentation
        3. Add in-app help system using tview
        4. Create quick reference guide
        5. Add help command (F1 or ?)
        
        **Help system features:**
        - In-app help dialog
        - Context-sensitive help
        - Quick reference guide
        - Searchable help system
        - Keyboard shortcuts overlay
        
        ## 📚 Resources
        - [tview documentation](https://pkg.go.dev/github.com/rivo/tview)
        - [TUI design patterns](https://github.com/rivo/tview/wiki)
        - [Keyboard shortcuts best practices](https://ux.stackexchange.com/questions/5226/standard-keyboard-shortcuts-for-desktop-applications)
