name: Semantic PRs

on:
  pull_request_target:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  validate_title:
    name: Validate Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          types: |
            fix
            feat
            improve
            refactor
            revert
            test
            ci
            docs
            chore
            upgrade
            update
            bump
            security
            perf
            style
            build
            deps

          scopes: |
            ui
            cli
            config
            parser
            deps
            security
            workflow
            makefile
            docker
            ci
          requireScope: false
          disallowScopes: false
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}" didn't match the configured pattern. Please ensure that the subject doesn't start with an uppercase character.
          validateSingleCommit: false
          ignoreLabels: |
            skip-semantic-pr
            hacktoberfest
          ignoreTitlePattern: |
            ^\[Hacktoberfest\]:
          ignoreCommits: |
            ^(Merge|Revert)
