name: Verify Fixes

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.23

            - name: Verify Go version
              run: go version

            - name: Download dependencies
              run: go mod download

            - name: Verify dependencies
              run: go mod verify

            - name: Run tests
              run: go test -v ./...

            - name: Build
              run: go build -v ./...

            - name: Test build
              run: go test -c ./...
